name: Singularity Build (native)
on: 
  push:

    # Edit the branches here if you want to change deploy behavior
    branches:
      - main
      - master

  # Do the builds on all pull requests (to test them)
  pull_request: []

jobs:
  changes:
    name: "Changed Singularity Recipes"
    runs-on: ubuntu-latest
    outputs:
      changed_file: ${{ steps.files.outputs.added_modified }}
    steps:
      - id: files
        uses: jitterbit/get-changed-files@b17fbb00bdc0c0f63fcf166580804b4d2cdc2a42
        with:
          format: 'json'
  
  build-test-containers:
    needs:
      - changes
    runs-on: ubuntu-latest
    strategy:
      # Keep going on other deployments if anything bloops
      fail-fast: false
      matrix:
        changed_file: ${{ fromJson(needs.changes.outputs.changed_file) }}

    name: Check ${{ matrix.changed_file }}
    steps:
      - name: Continue if Singularity Recipe
        run: |
          # Continue if we have a changed Singularity recipe
          if [[ "${{ matrix.changed_file }}" = *Singularity* ]]; then
            echo "keepgoing=true" >> $GITHUB_ENV
          fi          

      - name: Set up Go 1.13
        if: ${{ env.keepgoing == 'true' }}
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Install Dependencies
        if: ${{ env.keepgoing == 'true' }}
        run: |
          sudo apt-get update && sudo apt-get install -y \
            build-essential \
            libssl-dev \
            uuid-dev \
            libgpgme11-dev \
            squashfs-tools \
            libseccomp-dev \
            pkg-config \
            dh-autoreconf \
            curl-devel \
            expat-devel \
            gettext-devel \
            openssl-devel \
            perl-devel \
            zlib-devel \
          wget https://github.com/git/git/archive/refs/tags/v2.33.0.tar.gz 
          tar -xzf git-2.33.0.tar.gz
          cd git-2.33.0
          make configure
          ./configure --prefix=/usr
          make all doc info
          sudo make install install-doc install-html install-info
            
            

      - name: Install Singularity
        if: ${{ env.keepgoing == 'true' }}
        env:
          SINGULARITY_VERSION: 3.5.3
          GOPATH: /tmp/go
      
        run: |
          mkdir -p ${GOPATH}/src/github.com/hpcng && \
          cd ${GOPATH}/src/github.com/hpcng && \
          git clone https://github.com/hpcng/singularity.git && \
          cd singularity
          git checkout v3.5.2
          cd ${GOPATH}/src/github.com/hpcng/singularity && \
          ./mconfig && \
          cd ./builddir && \
          make && \
          sudo make install

      - name: Check out code for the container build
        if: ${{ env.keepgoing == 'true' }}
        uses: actions/checkout@v2

      - name: Build Container
        if: ${{ env.keepgoing == 'true' }}
        env:
          recipe: ${{ matrix.changed_file }}
        run: |
         ls 
         if [ -f "${{ matrix.changed_file }}" ]; then
            sudo -E singularity build container.sif ${{ matrix.changed_file }}
            tag=$(echo "${recipe/Singularity\./}")
            if [ "$tag" == "Singularity" ]; then
                tag=latest
            fi
            # Build the container and name by tag
            echo "Tag is $tag."
            echo "tag=$tag" >> $GITHUB_ENV
         else
           echo "${{ matrix.changed_file }} is not found."
           echo "Present working directory: $PWD"
           ls
         fi

      - name: Login and Deploy Container
        if: (github.event_name != 'pull_request')
        env:
          keepgoing: ${{ env.keepgoing }}
        run: |         
            if [[ "${keepgoing}" == "true" ]]; then
                echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io
                singularity push container.sif oras://ghcr.io/${GITHUB_REPOSITORY}:${tag}
            fi
